version: "3.1"

services:
  hso-web:
    image: odoo:19.0
    container_name: hso_logistic
    restart: unless-stopped
    depends_on:
      - hsodb
    ports:
      - "8055:8069"   # puerto web único
      - "8056:8072"   # puerto longpolling único
    volumes:
      - odoo-data-2:/var/lib/odoo
      - ./config2:/etc/odoo              # configuración específica de esta instancia
      - ./addons:/mnt/extra-addons      # módulos personalizados
    environment:
      - HOST=logisticdb
      - USER=odoo
      - PASSWORD=${ODOO_DB_PASSWORD:-odoo}
    command: >
      odoo
      --db_host=hsodb --db_port=5432
      --db_user=odoo --db_password=${ODOO_DB_PASSWORD:-odoo}
      --db-filter=.*
      --logfile=/var/log/odoo/odoo.log

  hsodb:
    image: postgres:16.0
    container_name: logisticdb
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres             # evita conflicto si ya existe "odoo"
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data-2:/var/lib/postgresql/data

volumes:
  odoo-data-2:
  db-data-2:
